---
on:
  push:
    branches:
      - GOLANG
  pull_request:
    branches:
      - GOLANG
name: Build and Push Image
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Store
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.RMODZ_TOKEN}}
      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/rcdevgames/wapi:latest
          docker push ghcr.io/rcdevgames/wapi:latest
